name: "Workshop"
description: "Workshop dokumentieren (DST, EventStorming, Example Mapping)"
labels: []

body:
  - type: markdown
    attributes:
      value: |
        ## Workshop-Dokumentation
        Erfasse die wichtigsten Informationen zum Workshop.

  - type: dropdown
    id: format
    attributes:
      label: Format
      options:
        - Domain Storytelling (DST)
        - EventStorming (ES)
        - Example Mapping (EM)
        - Review / Retrospektive
        - Sonstiges
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Datum
      placeholder: "YYYY-MM-DD"

  - type: textarea
    id: participants
    attributes:
      label: Teilnehmer
      placeholder: "Anna (Geotechnik), Ben (Entwicklung), ..."

  - type: textarea
    id: goal
    attributes:
      label: Ziel / Fragestellung
      description: Was soll im Workshop erreicht oder geklärt werden?
    validations:
      required: true

  - type: textarea
    id: artifacts
    attributes:
      label: Artefakte
      description: Links zu Whiteboards, Egon.io Exports, Dokumenten
      placeholder: "- Egon Export: docs/workshops/...\n- Miro Board: https://..."

  - type: textarea
    id: outcomes
    attributes:
      label: Ergebnisse & Nächste Schritte
      description: Entscheidungen, offene Fragen, Folgeaktionen
      placeholder: |
        **Entscheidungen:**
        - ...

        **Offene Fragen:**
        - ...

        **Nächste Schritte:**
        - [ ] Job Story erstellen: ...
        - [ ] Feature Issue: ...
    validations:
      required: true
