name: Workshop
description: Workshop-Dokumentation (z.B. DST, EventStorming, Example Mapping, Sonstiges)
title: "Workshop: <Kurzbeschreibung>"
labels: ["type:workshop","status:planned"]
# Optional: map to an org-level Issue Type if you've defined one
type: Workshop
# Optional: auto-add to a project (replace with your org/project IDs)
# projects: ["your-org/1"]

assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Workshop-Erfassung
        Bitte die wichtigsten Informationen zum Workshop eintragen.
        Pflichtfelder sind mit *erforderlich* markiert.

  - type: dropdown
    id: format
    attributes:
      label: Format
      description: Wähle das Workshop-Format aus
      options:
        - Domain Storytelling (DST)
        - EventStorming (ES)
        - Example Mapping (EM)
        - Review
        - Sonstiges
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Datum
      placeholder: "YYYY-MM-DD"

  - type: textarea
    id: goal
    attributes:
      label: Ziel / Fragestellungen
      description: Was soll im Workshop erreicht oder geklärt werden?
      placeholder: "z. B. MVP-Fähigkeiten für HS definieren; Kriterien für Schiefstellung abstimmen..."
    validations:
      required: true

  - type: textarea
    id: participants
    attributes:
      label: Teilnehmende
      description: Personen und Rollen
      placeholder: "Anna (Geotechnik), Ben (Risiko), Carla (PM)..."

  - type: textarea
    id: agenda
    attributes:
      label: Agenda (Ablauf)
      value: |
        - Begrüßung & Ziel (5 min)
        - Hauptaktivität (30–40 min)
        - Zusammenfassung & nächste Schritte (10 min)

  - type: textarea
    id: artifacts
    attributes:
      label: Artefakte / Links
      description: Verweise auf Whiteboards, Dokumente oder Slides
      placeholder: "docs/domain/…, egon export, etc."

  - type: textarea
    id: outcomes
    attributes:
      label: Ergebnisse & Nächste Schritte
      description: Entscheidungen, offene Fragen, Folgeaktionen
      placeholder: "- Entscheidung A …\n- Offen: …\n- Nächster Schritt: Features X, Y erstellen"
    validations:
      required: true
